interystore/authapp/urls.py
from django.urls import path, re_path, include
from authapp.views import user_login, user_logout, user_register, user_update, verify

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', user_login, name='login'),
    re_path(r'^logout/$', user_logout, name='logout'),
    re_path(r'^register/$', user_register, name='register'),
    re_path(r'^edit/$', user_update, name='update'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', verify, name='verify')

]

interystore/interystore/urls.py
from django.contrib import admin
from django.urls import path, re_path, include


urlpatterns = [
    re_path(r'^', include('mainapp.urls', namespace='main')),
    re_path(r'auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', admin.site.urls),
]

interystore/mainapp/urls.py
from django.urls import path, re_path
from mainapp.views import products, detail, contacts, main, product
from django.conf import settings
from django.conf.urls.static import static

app_name = 'mainapp'

urlpatterns = [
    re_path(r'^$', main, name='main'),
    re_path(r'^detail/$', detail, name='detail'),
    re_path(r'^products/$', products, name='products'),
    re_path(r'^catalog/category/(\d+)/$', product, name='catalog'),
    re_path('^catalog/product/(?P<pk>\d+)/$', product, name='product'),
    re_path(r'^contacts/$', contacts, name='contacts'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

interystore/authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.timezone import now
from datetime import timedelta


def get_now():
    return now() + timedelta(hours=48)


class ShopUser(AbstractUser):
    avatar = models.ImageField(
        upload_to='users_avatars',
        blank=True,
    )

    age = models.SmallIntegerField(
        verbose_name='возраст'
    )

    activation_key = models.CharField(
        max_length=128,
        blank=True
    )

    activation_key_expire = models.DateTimeField(
        default=get_now
    )

    def is_activation_key_expared(self):
        if now() <= self.activation_key_expire:
            return False
        else:
            return True

interystore/authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, forms, UserChangeForm
from authapp.models import ShopUser

import hashlib
import random

class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model =ShopUser
        filed = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'password1', 'password2', 'email', 'age', 'avatar')


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidateError("Вы слишком молоды")

        return data

    def save(self):
        user = super().save()
        user.is_active = False
        salt = hashlib.sha1(str(random.random()).encode('utf8')).hexdigest()[:6]
        user.activation_key = hashlib.sha1((user.email + salt).encode('utf8')).hexdigest()
        user.save()

        return user

class ShopUserChangeForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'password', 'email', 'age', 'avatar')


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidateError("Вы слишком молоды")

        return data

interystore/authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from authapp.forms import ShopUserLoginForm, ShopUserRegisterForm, ShopUserChangeForm
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.conf import settings
from django.core.mail import send_mail
from .models import ShopUser

def user_login(request):

    if request.method == 'POST':
        form = ShopUserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            print("Форма заполнена корректно")
            if user:
                login(request, user)
                # return HttpResponseRedirect('/')
                return HttpResponseRedirect(reverse('main:main'))

    else:
        form = ShopUserLoginForm()

    context = {
        'form': form,
    }
    return render(request, 'authapp/login.html', context)


def user_logout(request):

    logout(request)
    return HttpResponseRedirect(reverse('main:main'))

def user_register(request):
    if request.method == 'POST':
        form = ShopUserRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            if send_verify_email(user):
                print('сообщение подтверждения отправлено')
                return HttpResponseRedirect(reverse('main:main'))
            else:
                print('ошибка отправки сообщения')
                return HttpResponseRedirect(reverse('auth:login'))
    else:
        form = ShopUserRegisterForm()

    context = {
        'form': form,
    }
    return render(request, 'authapp/register.html', context)


def user_update(request):

    if request.method == 'POST':
        form = ShopUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse('main:main'))

    else:
        form = ShopUserChangeForm(instance=request.user)

    context = {
        'form': form,
    }
    return render(request, 'authapp/register.html', context)


def send_verify_email(user):
    verify_link = reverse('auth:verify', args=[user.email, user.activation_key])

    title = f'Подтверждение учетной записи {user.username}'

    message = f'Для подтверждения учетной записи {user.username} на портале {settings.DOMAIN_NAME} \
                перейти по ссылке: \n{settings.DOMAIN_NAME}{verify_link}'

    return send_mail(title, message, settings.EMAIL_HOST_USER, [user.email], fail_silently=False)


def verify(request, email, activation_key):
    try:
        user = ShopUser.objects.get(email=email)
        if user.activation_key == activation_key and not user.activation_key_expire:
            user.is_active = True
            user.save()
            login(request, user)
        else:
            print(f'error activation user: {user}')
        return render(request, 'authapp/verification.html')
    except Exception as e:
        print(f'error activation user: {e} -> {e.args}')
        return HttpResponseRedirect(reverse('main:main'))

interystore/authapp/templates/authapp/edit.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %}
    {{ page_title|title }}
{% endblock %}

    {% block container %}
        <div class="slider-head">
            <div class="header  padding-site">
                <a class="logo" href="/"><img src="{% static 'img/logo.png' %}" alt="logo"></a>
                <div>
                    {% include 'mainapp/includes/inc__menu_top.html' %}
                </div>

            </div>
            <div class="pd-head">
                <h1>Обновить данные пользователя</h1>
            </div>
        </div>

            <div class="login">

                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Сохранить" class="btn btn-primary">

                </form>
            </div>

    {% endblock %}

interystore/authapp/templates/authapp/login.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %}
    {{ page_title|title }}
{% endblock %}

    {% block container %}
        <div class="slider-head">
            <div class="header  padding-site">
                <a class="logo" href="/"><img src="{% static 'img/logo.png' %}" alt="logo"></a>
                <div>
                    {% include 'mainapp/includes/inc__menu_top.html' %}
                </div>

            </div>
            <div class="pd-head">
                <h1>Подтверждение</h1>
            </div>
        </div>

            <div class="login">

                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Войти" class="btn btn-primary">

                </form>
                <a href="{% url 'auth:register' %}" class="btn btn-round from-control">зарегистрироваться</a>
            </div>

    {% endblock %}

interystore/authapp/templates/authapp/register.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %}
    {{ page_title|title }}
{% endblock %}

    {% block container %}
        <div class="slider-head">
            <div class="header  padding-site">
                <a class="logo" href="/"><img src="{% static 'img/logo.png' %}" alt="logo"></a>
                <div>
                    {% include 'mainapp/includes/inc__menu_top.html' %}
                </div>

            </div>
            <div class="pd-head">
                <h1>Регистрация пользователя</h1>
            </div>
        </div>

            <div class="login">

                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Войти" class="btn btn-primary">

                </form>
            </div>

    {% endblock %}

interystore/authapp/templates/authapp/verification.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %}
{{ page_title|title }}
{% endblock %}

{% block container %}
<div class="slider-head">
    <div class="header  padding-site">
        <a class="logo" href="/"><img src="{% static 'img/logo.png' %}" alt="logo"></a>
        <div>
            {% include 'mainapp/includes/inc__menu_top.html' %}
        </div>

    </div>
    <div class="pd-head">
        <h1>Вход пользователя</h1>
    </div>
</div>
<div class="login">
    {% if user %}
    <h3>Поздравляем!</h3>
    <br>
    <h4>Пользователь {{user.username}} подтвержден.</h4>
    {% else %}
    <h3>Верификация не пройдена.</h3>
    {% endif %}
    <br>
    <button class="btn btn-round form-control">
        <a href="{% url 'main:main' %}" class="">
            на главную
        </a>
    </button>
</div>
{% endblock %}