interystore/authapp/urls.py
from django.urls import path, re_path, include
from authapp.views import user_login, user_logout, user_register, user_update, verify

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', user_login, name='login'),
    re_path(r'^logout/$', user_logout, name='logout'),
    re_path(r'^register/$', user_register, name='register'),
    re_path(r'^edit/$', user_update, name='update'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', verify, name='verify')

]

interystore/basketapp/urls.py
from django.urls import re_path
import basketapp.views as basketapp


app_name = 'basket'

urlpatterns = [
    re_path(r'^$', basketapp.index, name='index'),
    re_path(r'^add/(?P<product_pk>\d+)/$', basketapp.basket_add, name='add'),
]

interystore/interystore/urls.py
from django.contrib import admin
from django.urls import path, re_path, include


urlpatterns = [
    re_path(r'^', include('mainapp.urls', namespace='main')),
    re_path(r'auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', admin.site.urls),
]

interystore/mainapp/urls.py
from django.urls import path, re_path
from mainapp.views import products, detail, contacts, main, product
from django.conf import settings
from django.conf.urls.static import static

app_name = 'mainapp'

urlpatterns = [
    re_path(r'^$', main, name='main'),
    re_path(r'^detail/$', detail, name='detail'),
    re_path(r'^products/$', products, name='products'),
    re_path(r'^catalog/category/(\d+)/$', product, name='catalog'),
    re_path('^catalog/product/(?P<pk>\d+)/$', product, name='product'),
    re_path(r'^contacts/$', contacts, name='contacts'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

interystore/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(
        verbose_name='имя категории',
        max_length=45,
        unique=True
    )

    description = models.TextField(
        verbose_name='описание',
        blank=True

    )

    def __str__(self):
        return f'ProductCategory: {self.name} {self.pk}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'




class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE
    )
    name = models.CharField(
        verbose_name='имя продукта',
        max_length=128
    )
    image = models.ImageField(
        upload_to='product_images',
        blank=True
    )
    short_desc = models.TextField(
        verbose_name='краткое описание продукта',
        max_length=60,
        blank=True
    )
    description = models.TextField(
        verbose_name='описание продукта',
        blank=True
    )
    price = models.DecimalField(
        verbose_name='цена продукта',
        max_digits=8,
        decimal_places=2
    )
    quantity = models.PositiveIntegerField(
        verbose_name='количество на складе',
        default=0
    )


    def __str__(self):
        return f'Product: {self.name} {self.pk}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

interystore/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from mainapp.models import ProductCategory, Product
import random

def get_basket(user):
    if user.is_authenticated:
        return user.basket_set.all().order_by('product__category')
    return []

def main(request):
    context = {
        'title': 'главная',
        'basket': get_basket(request.user),
    }
    return render(request, 'mainapp/index.html', context)


def products(request, category_pk=None):
    categories = ProductCategory.objects.all()
    products = Product.objects.all()
    if category_pk:
        if category_pk != '0':
            products = Product.objects.filter(category__pk=category_pk)
        context = {
            'title': 'каталог',
            'products': products,
            'categories': categories,
            'basket': get_basket(request.user),
        }
        return render(request, 'mainapp/products_list.html', context)
    else:
        hot_product = random.choice(products)
        same_products = Product.objects.filter(category=hot_product.category). \
            exclude(pk=hot_product.pk)

        context = {
            'title': 'каталог',
            'categories': categories,
            'basket': get_basket(request.user),
            'hot_product': hot_product,
            'same_products': same_products,
        }
        return render(request, 'mainapp/products.html', context)


def product(request, pk):
    categories = ProductCategory.objects.all()

    context = {
        'title': 'продукты',
        'categories': categories,
        'product': get_object_or_404(Product, pk=pk),
        'basket': get_basket(request.user),
    }

    return render(request, 'mainapp/products.html', context)


def detail(request):
    basket = []
    if request.user.is_authenticated:
        basket = request.user.basket_set.all()

    context = {
        'page_title': 'детали',
    }
    return render(request, 'mainapp/detail.html', context)


def contacts(request):
    basket = []
    if request.user.is_authenticated:
        basket = request.user.basket_set.all()

    locations = [
        {
            'city': 'COLIFORNIA',
            'phone': '1900-1234-5678',
            'email': 'info@interior.com',
            'address': '12 W 1st St. 90001 Los Angeles. Colifornia',
        },
        {
            'city': 'LONDON',
            'phone': '+49-324-424-4444',
            'email': 'info@interior.com',
            'address': '12 W 1st St. 90001 Los Angeles. Colifornia',
        },
        {
            'city': 'SINGAPUR',
            'phone': '1900-1234-5678',
            'email': 'info@interior.com',
            'address': '12 W 1st St. 90001 Los Angeles. Colifornia',
        }

    ]


    context = {
        'page_title': 'контакты',
        'locations': locations,
    }
    return render(request, 'mainapp/contacts.html', context)

interystore/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {{ page_title|title }}
        {% endblock %}

    </title>
    {% block style %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Montserrat:100,300,400,700" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>

<body>
    <div class="container">

        {% block container %}
        {% endblock %}

        {% block footer %}
            <footer>
                <div class="footer-links">
                    <div class="col">
                        <div class="block-header">
                            <h3>Contact Us</h3>
                        </div>
                        <p>132A Bridge Road Richmond VIC
                            Australia. </p>
                        <p>
                            Talk to us on 1300 132
                            info@interior.com</p>


                    </div>
                    <div class="col">
                        <div class="block-header">
                            <h3>Useful Information</h3>
                        </div>
                        <div class="link-w">
                            <a href="">Sales terms</a>
                            <a href="">Customer care</a>
                            <a href="">Delivery</a>
                        </div>
                    </div>
                    <div class="col">
                        <div class="block-header"></div>
                        <div class="link-w">
                            <a href="">Architect accounts</a>
                            <a href="">Careers</a>
                            <a href="">Exchanges & returns</a>
                        </div>
                    </div>
                    <div class="col">
                        <div class="block-header">
                            <h3>Let’s Stay in Touch!</h3>
                        </div>
                        <p class="w-w">Suscribe to know about our latest news, products and special offers just for suscribers.</p>
                        <input type="email">
                        <a href="#" class="subcrib"><i class="fab fa-telegram-plane"></i></a>
                    </div>

                    <div class="social-link">
                        <div class="col-2 copy">© Copyright - INTERIOR 2016. All Rights Reserved.</div>
                        <div class="col-3">
                            <a href=""><i class="fab fa-facebook-f"></i></a>
                            <a href=""><i class="fab fa-twitter"></i></a>
                            <a href=""><i class="fab fa-google-plus-g"></i></a>
                            <a href=""><i class="fab fa-pinterest"></i></a>
                        </div>
                        <div class="col-2 terms">
                            <a href="">Terms & Conditions</a> /<a href=""> Privacy policy & Cookies</a>
                        </div>


                    </div>
                </div>
            </footer>
        {% endblock %}
    </div>
</body>

</html>

interystore/mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %}
    {{ page_title|title }}
{% endblock %}

    {% block container %}
        <div class="slider-head">
            <div class="header  padding-site">
                <a class="logo" href="/"><img src="{% static 'img/logo.png' %}" alt="logo"></a>
                <div>
                    {% include 'mainapp/includes/inc__menu_top.html' %}
                </div>

            </div>
            <div class="pd-head">
                <h1>Contacts</h1>
            </div>
        </div>

            <div class="contacts">
            <div class="row">
                {% if locations %}
                {% for location in locations %}
                <div class="cont-block">
                    <i class="fas fa-map-marker-alt"></i>
                    <h3>{{ location.city }}</h3>
                    <p class="pea"><span>Phone:<br /></span> <strong>{{ location.phone }}</strong></p>
                    <p class="pea"><span>Email:<br /></span><strong>{{ location.email }}</strong></p>
                    <p class="pea"><span>Address:<br /></span>{{ location.address}}</p>
                </div>
                {% endfor %}
                {% else %}
                    <h2>Нечего показать</h2>

                {% endif %}

            </div>

        </div>



    {% endblock %}

interystore/mainapp/templates/mainapp/detail.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title%}
    {{ page_title|title }}
{% endblock %}

    {% block container %}
        <div class="slider slider-head">
            <div class="header  padding-site">
                <a class="logo" href="index.html"><img src="/static/img/logo.png" alt="logo"></a>
                <div>
                    {% include 'mainapp/includes/inc__menu_top.html' %}
                </div>

            </div>
            <div class="menu-detail">
                {% include 'mainapp/includes/inc__menu_products.html' %}
            </div>
        </div>
        <div class="detail">
            <div class="photo">
                <img src="/static/img/slider1.png" alt="">
                <div class="thumb">
                    <a href="#"><img src="/static/img/controll.png" alt=""></a>
                    <a href="#"><img src="/static/img/controll11.png" alt=""></a>
                    <a href=""><img src="/static/img/controll2.png" alt=""></a>
                </div>
            </div>
            <div class="detail-info">
                <h2>Fishnet Chair</h2>
                <h5>Hot deal</h5>
                <div class="price"><span>$</span>36.7<span>/sq</span></div>
                <a href="#" class="button redbtn">Order us&#62;</a>
                <p>The majesty of Mountains - Ugmonk style.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore
                    et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
            </div>

        </div>

        <div class="treding">
            <div class="fea-links tred-bord">
                <p class="tred-a">Related Products</p>
                <a href="#">Explore all<span>&#8250;</span></a>
            </div>

            <div class="tren-product">
                <div class="tren-pd">
                    <img src="/static/img/product-11.png" alt="" class="" id="">
                </div>
                <div class="tren-pd">
                    <img src="/static/img/product-41.png" alt="" class="" id="">
                </div>
                <div class="tren-pd">

                    <img src="/static/img/product-21.png" alt="" class="" id="">
                </div>
                <div class="tren-pd">

                    <img src="/static/img/product-5.png" alt="" class="" id="">
                </div>
                <div class="tren-pd">

                    <img src="/static/img/product-31.png" alt="" class="" id="">
                </div>
                <div class="tren-pd">
                    <img src="/static/img/product-6.png" alt="" class="" id="">
                </div>

            </div>
        </div>

        {% endblock %}

interystore/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
    {% block container %}
        <div class="slider padding-site">
            <div class="header">
                <a class="logo" href="#"><img src="{% static 'img/logo.png' %}" alt="logo"></a>
                {% include 'mainapp/includes/inc__menu_top.html' %}
            </div>
            <div class="header-text">
                <h3 class="slider-h3">TRENDING</h3>
                <h2 class="slider-h2">Fishnet Chair</h2>
                <p class="slider-text">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black</p>
                <a href="#" class="button">Order us<span>&#8250;</span></a>
            </div>
            <div class="pagination">
                <a href="#" class="circle"></a>
                <a href="#" class="circle circle-active"></a>
                <a href="#" class="circle"></a>
            </div>
        </div>
        <div class="futured content">
            <div class="fea-links">
                <a href="#">Featured</a>
                <a href="#">New</a>
                <a href="/products/">Explore all<span>&#8250;</span></a>
            </div>

            <div class="fea-products">
                <div class="fea-pd">
                    <div class="fea-pd-control">
                        <a href="{% url 'main:detail' %}" class="fea-pd-control-a">&#8250;</a>
                        <h3 class="fea-pd-title">Fishnet Chair</h3>
                        <p>Seat and back with upholstery made of cold cure</p>

                    </div>
                    <img src="{% static 'img/product-2.png' %}" alt="" class="" id="">

                </div>

                <div class="fea-pd">
                    <div class="fea-pd-control">
                        <a href="/detail/" class="fea-pd-control-a">&#8250;</a>
                        <h3 class="fea-pd-title">Fishnet Chair</h3>
                        <p>Seat and back with upholstery made of cold cure</p>

                    </div>
                    <img src="{% static 'img/product-2.png' %}" alt="" class="" id="">
                </div>
                <div class="fea-pd">
                    <div class="fea-pd-control">
                        <a href="/detail/" class="fea-pd-control-a">&#8250;</a>
                        <h3 class="fea-pd-title">Fishnet Chair</h3>
                        <p>Seat and back with upholstery made of cold cure</p>

                    </div>
                    <img src="{% static 'img/product-3.png' %}" alt="" class="" id="">
                </div>
                <div class="fea-pd">
                    <div class="fea-pd-control">
                        <a href="/detail/" class="fea-pd-control-a">&#8250;</a>
                        <h3 class="fea-pd-title">Fishnet Chair</h3>
                        <p>Seat and back with upholstery made of cold cure</p>

                    </div>
                    <img src="{% static 'img/product-4.png' %}" alt="" class="" id="">
                </div>

            </div>
        </div>
        <div class="featured-big">
            <div class="fea-big-block fea-2img">

                <div class="fea-big-text">
                    <h3 class="slider-h3">EXCLUSIVE</h3>
                    <h2 class="slider-h2 text-wu-tf">Fishnet Chair</h2>
                    <p class="slider-text">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black</p>
                    <a href="#" class="button">Order us<span>&#8250;</span></a>
                </div>
            </div>
            <div class="fea-big-block fea-3img">

                <div class="fea-big-text">
                    <h3 class="slider-h3">EXCLUSIVE</h3>
                    <h2 class="slider-h2 text-wu-tf">Fishnet Chair</h2>
                    <p class="slider-text">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black</p>
                    <a href="#" class="button">Order us<span>&#8250;</span></a>
                </div>
            </div>

        </div>
        <div class="treding content">
            <div class="fea-links tred-bord">
                <p class="tred-a">Trending Products</p>
                <a href="/products/">Explore all<span>&#8250;</span></a>
            </div>

            <div class="tren-product">
                <div class="tren-pd">
                   <a href="/detail/">
                    <img src="{% static 'img/product-11.png' %}" alt="" class="" id=""></a>
                </div>
                <div class="tren-pd">
                   <a href="/detail/">
                       <img src="{% static 'img/product-41.png' %}" alt="" class="" id=""></a>
                </div>
                <div class="tren-pd">
                    <a href="/detail/">
                        <img src="{% static 'img/product-21.png' %}" alt="" class="" id=""></a>
                </div>
                <div class="tren-pd">
                    <a href="/detail/">
                        <img src="{% static 'img/product-5.png' %}" alt="" class="" id=""></a>
                </div>
                <div class="tren-pd">
                    <a href="/detail/">
                        <img src="{% static 'img/product-31.png' %}" alt="" class="" id=""></a>
                </div>
                <div class="tren-pd">
                   <a href="/detail/">
                       <img src="{% static 'img/product-6.png' %}" alt="" class="" id=""></a>
                </div>

            </div>
        </div>
        <div class="slider2">

            <div class="sl2-header-text">
                <h3 class="slider-h3 hot">HOT DEAL</h3>
                <h2 class="slider-h2">Fishnet Chair</h2>
                <p class="slider-text">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black</p>
                <a href="#" class="button">Order us<span>&#8250;</span></a>
            </div>
            <div class="pagination">
                <a href="#" class="circle"></a>
                <a href="#" class="circle circle-active"></a>
                <a href="#" class="circle"></a>
            </div>
        </div>
        <div class="acessuars content">
            <div class="ac-big">

                <div class="fea-big-text one-fa">
                    <h3 class="slider-h3">Exclusive</h3>
                    <h2 class="slider-h2 text-wu-tf">Fishnet Chair</h2>
                    <p class="slider-text">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black</p>
                    <a href="#" class="button">Order us<span>&#8250;</span></a>
                </div>
            </div>
            <div class="acc-big">
                <a href="#" class="pd1 pd-size"></a>
                <a href="#" class="pd2 pd-size"></a>
                <a href="#" class="pd3 pd-size"></a>
                <a href="#" class="pd4 pd-size"></a>
            </div>
        </div>
        <div class="mobile">

            <div class="mob-text-block">
                <div class="block-title">
                    <p>mobile app</p>
                </div>
                <div class="block-head-text">
                    <p>Find. Follow. Favorite.</p>
                </div>
                <p>Save your favorites and share your style.</p>
                <div class="store-link">
                    <a href="#">
                        <img src="{% static 'img/app-store.png' %}" alt=""></a>
                    <a href="#">
                        <img src="{% static 'img/google-play.png' %}" alt=""></a>
                </div>
            </div>
        </div>
    {% endblock %}

interystore/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title%}
    {{ page_title|title }}
{% endblock %}

    {% block container %}
        <div class="slider-head">
            <div class="header  padding-site">
                <a class="logo" href="/"><img src="{% static 'img/logo.png' %}" alt="logo"></a>
                <div>
                    {% include 'mainapp/includes/inc__menu_top.html' %}
                </div>

            </div>
            <div class="pd-head">
                <h1>Our products</h1>
            </div>
        </div>
        <div class="treding content">
               <div class="fea-links-pd">
                    {% include 'mainapp/includes/inc__menu_products.html' %}
            </div>
            <div class="tren-product">
                {% for product in same_products %}
                <div class="tren-pd">
                   <a href="{% url 'basket:add' product.pk %}">
                       <img src="/media/{{ product.image|default:'product_images/default.jpeg'}}" alt="" class="" id=""></a>
                </div>

                {% endfor %}

            </div>
        </div>
        <div class="featured-big">
            <div class="fea-big-block fea-2img">

                <div class="fea-big-text">
                    <h3 class="slider-h3">EXCLUSIVE</h3>
                    <h2 class="slider-h2 text-wu-tf">Fishnet Chair</h2>
                    <p class="slider-text">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black</p>
                    <a href="#" class="button">Order us<span>&#8250;</span></a>
                </div>
            </div>
            <div class="fea-big-block fea-3img">

                <div class="fea-big-text">
                    <h3 class="slider-h3">EXCLUSIVE</h3>
                    <h2 class="slider-h2 text-wu-tf">Fishnet Chair</h2>
                    <p class="slider-text">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black</p>
                    <a href="#" class="button">Order us<span>&#8250;</span></a>
                </div>
            </div>

        </div>

    {% endblock %}

interystore/mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title%}
    {{ page_title|title }}
{% endblock %}

    {% block container %}
        <div class="slider-head">
            <div class="header  padding-site">
                <a class="logo" href="/"><img src="{% static 'img/logo.png' %}" alt="logo"></a>
                <div>
                    {% include 'mainapp/includes/inc__menu_top.html' %}
                </div>

            </div>
            <div class="pd-head">
                <h1>{% if request.resolver_match.args.0 == '0' %}
                        ВСЕ
                    {% else %}
                        {{ products.0.category.name|title }}
                    {% endif %}</h1>
            </div>
        </div>
        <div class="treding content">
               <div class="fea-links-pd">
                    {% include 'mainapp/includes/inc__menu_products.html' %}
            </div>
            <div class="tren-product">
                {% for product in products %}
                <div class="tren-pd">
                   <a href="{% url 'basket:add' product.pk %}">
                       <img src="/media/{{ product.image|default:'product_images/default.jpeg'}}" alt="" class="" id=""></a>
                </div>

                {% endfor %}

            </div>
        </div>
        <div class="featured-big">
            <div class="fea-big-block fea-2img">

                <div class="fea-big-text">
                    <h3 class="slider-h3">EXCLUSIVE</h3>
                    <h2 class="slider-h2 text-wu-tf">Fishnet Chair</h2>
                    <p class="slider-text">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black</p>
                    <a href="#" class="button">Order us<span>&#8250;</span></a>
                </div>
            </div>
            <div class="fea-big-block fea-3img">

                <div class="fea-big-text">
                    <h3 class="slider-h3">EXCLUSIVE</h3>
                    <h2 class="slider-h2 text-wu-tf">Fishnet Chair</h2>
                    <p class="slider-text">Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black</p>
                    <a href="#" class="button">Order us<span>&#8250;</span></a>
                </div>
            </div>

        </div>

    {% endblock %}