interystore/authapp/urls.py
from django.urls import path, re_path, include
from authapp.views import user_login, user_logout, user_register, user_update, verify

app_name = 'authapp'

urlpatterns = [
    re_path(r'^login/$', user_login, name='login'),
    re_path(r'^logout/$', user_logout, name='logout'),
    re_path(r'^register/$', user_register, name='register'),
    re_path(r'^edit/$', user_update, name='update'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', verify, name='verify')

]

interystore/basketapp/urls.py
from django.urls import re_path
import basketapp.views as basketapp


app_name = 'basket'

urlpatterns = [
    re_path(r'^$', basketapp.index, name='index'),
    re_path(r'^add/(?P<product_pk>\d+)/$', basketapp.basket_add, name='add'),
]

interystore/interystore/urls.py
from django.contrib import admin
from django.urls import path, re_path, include


urlpatterns = [
    re_path(r'^', include('mainapp.urls', namespace='main')),
    re_path(r'auth/', include('authapp.urls', namespace='auth')),
    re_path(r'^basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', admin.site.urls),
]

interystore/mainapp/urls.py
from django.urls import path, re_path
from mainapp.views import products, detail, contacts, main, product
from django.conf import settings
from django.conf.urls.static import static

app_name = 'mainapp'

urlpatterns = [
    re_path(r'^$', main, name='main'),
    re_path(r'^detail/$', detail, name='detail'),
    re_path(r'^products/$', products, name='products'),
    re_path(r'^catalog/category/(\d+)/$', product, name='catalog'),
    re_path('^catalog/product/(?P<pk>\d+)/$', product, name='product'),
    re_path(r'^contacts/$', contacts, name='contacts'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

interystore/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(
        verbose_name='имя категории',
        max_length=45,
        unique=True
    )

    description = models.TextField(
        verbose_name='описание',
        blank=True

    )

    def __str__(self):
        return f'ProductCategory: {self.name} {self.pk}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'




class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE
    )
    name = models.CharField(
        verbose_name='имя продукта',
        max_length=128
    )
    image = models.ImageField(
        upload_to='product_images',
        blank=True
    )
    short_desc = models.TextField(
        verbose_name='краткое описание продукта',
        max_length=60,
        blank=True
    )
    description = models.TextField(
        verbose_name='описание продукта',
        blank=True
    )
    price = models.DecimalField(
        verbose_name='цена продукта',
        max_digits=8,
        decimal_places=2
    )
    quantity = models.PositiveIntegerField(
        verbose_name='количество на складе',
        default=0
    )


    def __str__(self):
        return f'Product: {self.name} {self.pk}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

interystore/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from mainapp.models import ProductCategory, Product
import random

def get_basket(user):
    if user.is_authenticated:
        return user.basket_set.all().order_by('product__category')
    return []

def main(request):
    context = {
        'title': 'главная',
        'basket': get_basket(request.user),
    }
    return render(request, 'mainapp/index.html', context)


def products(request, category_pk=None):
    categories = ProductCategory.objects.all()
    products = Product.objects.all()
    if category_pk:
        if category_pk != '0':
            products = Product.objects.filter(category__pk=category_pk)
        context = {
            'title': 'каталог',
            'products': products,
            'categories': categories,
            'basket': get_basket(request.user),
        }
        return render(request, 'mainapp/products_list.html', context)
    else:
        hot_product = random.choice(products)
        same_products = Product.objects.filter(category=hot_product.category). \
            exclude(pk=hot_product.pk)

        context = {
            'title': 'каталог',
            'categories': categories,
            'basket': get_basket(request.user),
            'hot_product': hot_product,
            'same_products': same_products,
        }
        return render(request, 'mainapp/products.html', context)


def product(request, pk):
    categories = ProductCategory.objects.all()

    context = {
        'title': 'продукты',
        'categories': categories,
        'product': get_object_or_404(Product, pk=pk),
        'basket': get_basket(request.user),
    }

    return render(request, 'mainapp/products.html', context)


def detail(request):
    basket = []
    if request.user.is_authenticated:
        basket = request.user.basket_set.all()

    context = {
        'page_title': 'детали',
    }
    return render(request, 'mainapp/detail.html', context)


def contacts(request):
    basket = []
    if request.user.is_authenticated:
        basket = request.user.basket_set.all()

    locations = [
        {
            'city': 'COLIFORNIA',
            'phone': '1900-1234-5678',
            'email': 'info@interior.com',
            'address': '12 W 1st St. 90001 Los Angeles. Colifornia',
        },
        {
            'city': 'LONDON',
            'phone': '+49-324-424-4444',
            'email': 'info@interior.com',
            'address': '12 W 1st St. 90001 Los Angeles. Colifornia',
        },
        {
            'city': 'SINGAPUR',
            'phone': '1900-1234-5678',
            'email': 'info@interior.com',
            'address': '12 W 1st St. 90001 Los Angeles. Colifornia',
        }

    ]


    context = {
        'page_title': 'контакты',
        'locations': locations,
    }
    return render(request, 'mainapp/contacts.html', context)

interystore/mainapp/templates/mainapp/includes/inc__menu_products.html
                <ul>
                    <li class="{% if request.resolver_match.args.0 == '0' %}
                       menu-list  menu-link-active
                       {% else %}
                       menu-list
                    {% endif %}">
                        <a href="{% url 'main:catalog' 0 %}">ALL</a>
                    </li>
                    {% for category in categories %}

                    <li class="{% if request.resolver_match.args.0|add:0 == category.pk %}
                       menu-list  menu-link-active
                       {% else %}
                       menu-list
                    {% endif %}">
                        <a href="{% url 'main:catalog' category.pk %}">{{ category.name }}</a>
                    </li>
                    {% endfor %}
                </ul>

interystore/mainapp/templates/mainapp/includes/inc__menu_top.html
               {% load static %}
                <ul class="menu">
                    <li class="menu-list">
                        <a href="{% url 'main:main' %}" class="menu-link
                        {% if request.resolver_match.url_name == 'main:main' %}menu-link-active {% endif %}">HOME</a></li>
                    <li class="menu-list">
                        <a href="{% url 'main:products' %}" class="menu-link
                        {% if request.resolver_match.url_name == 'products' %}menu-link-active {% endif %}">PRODUCTS</a></li>
                    <li class="menu-list">
                        <a href="{% url 'main:contacts' %}" class="menu-link
                        {% if request.resolver_match.url_name == 'contacts' %}menu-link-active {% endif %}">CONTACT</a></li>

                    <li class="menu-list">
                        {% if user.is_authenticated %}
                            <a href="{% url 'auth:logout' %}" class="menu-link
                        {% if request.resolver_match.url_name == 'logout' %}menu-link-active {% endif %}">выйти</a>
                        {% else %}
                            <a href="{% url 'auth:login' %}" class="menu-link
                        {% if request.resolver_match.url_name == 'login' %}menu-link-active {% endif %}">войти</a>
                        {% endif %}
                    </li>
                    <li class="menu-list user-name ">
                        {% if user.is_authenticated %}
                        <a href="{% url 'auth:update' %}">
                            {{ user.first_name|default:'Пользователь' }}
                            </a>
                        {% endif %}
                    </li>
                    <li class="search">
                        <img src="{% static 'img/search%20(5).svg' %}" alt="search">
                    </li>
                    <li class="search">

                            {% if basket %}
                                <a href="{% url 'basket:index' %}">
                                <i class="fa fa-shopping-cart"></i>
                                    <span>

                                    {{ basket.0.total_cost|floatformat:0 }} $.
                                    ({{ basket.0.total_quantity }}) itm.
                                    </span>
                                </a>
                            {% endif %}
                    </li>
                </ul>